modLoader="javafml" #mandatory
loaderVersion="[2,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All Rights Reserved"

[[mods]] #mandatory
modId="ebalchemy"
version="0.2.1"
displayName="Eba's Alchemy"
issueTrackerURL="https://github.com/Mithion/Mystic-Alchemy/issues"

# A text field displayed in the mod UI
credits="Thanks to the M&A community for helping me with ideas!  Thanks to Geolykt for the translation!"
authors="Mithion, Evaisa"
description='''Expands potions and brewing in the game to be more dynamic, and magical.'''

[[dependencies.ebalchemy]]
    modId="forge"
    mandatory=true
    versionRange="[47.1,48)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ebalchemy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    sides="BOTH"